# Generated by Django 2.2.4 on 2019-12-23 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(default=1)),
                ('name', models.CharField(default='Hà Nội', max_length=100)),
            ],
        ),
    ]
