# Generated by Django 2.2.4 on 2019-12-23 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='province',
            name='code',
            field=models.CharField(default='1', max_length=10),
        ),
    ]
