# Generated by Django 2.2.4 on 2019-12-23 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20191224_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='province',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
