# Generated by Django 2.2.4 on 2019-12-24 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20191224_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='logo',
            field=models.CharField(default='', max_length=255),
        ),
    ]
