# Generated by Django 2.2.4 on 2019-12-26 09:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20191226_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='rate',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
